// --- Player Archetype Database ---
// This file maps player names to their core skills for synergy analysis.
// This allows the static script.js to perform a "synergy" analysis.

export const ARCHETYPES = {
    // --- POINT GUARDS ---
    "Shai Gilgeous-Alexander": ["SCORING", "PLAYMAKER", "DEFENSE_PER"],
    "Luka Dončić (LAL)": ["SCORING", "PLAYMAKER", "REBOUNDING"],
    "Jalen Brunson": ["SCORING", "PLAYMAKER"],
    "Tyrese Haliburton": ["PLAYMAKER", "SPACING"],
    "Stephen Curry": ["SCORING", "SPACING", "PLAYMAKER"],
    "Anthony Edwards": ["SCORING", "PLAYMAKER", "DEFENSE_PER"],
    "Tyrese Maxey": ["SCORING", "SPACING"],
    "Trae Young": ["PLAYMAKER", "SCORING"],
    "Cade Cunningham": ["PLAYMAKER", "SCORING"],
    "Ja Morant": ["SCORING", "PLAYMAKER"],
    "De'Aaron Fox (SAN)": ["SCORING", "PLAYMAKER"],
    "Jamal Murray": ["SCORING"],
    "LaMelo Ball": ["PLAYMAKER"],
    "Donovan Mitchell": ["SCORING"],
    "Darius Garland": ["PLAYMAKER", "SCORING"],
    "Coby White": ["SCORING", "SPACING"],
    "Amen Thompson (HOU)": ["PLAYMAKER", "DEFENSE_PER", "PROJECT"],
    "Jrue Holiday (POR)": ["PLAYMAKER", "DEFENSE_PER"],
    "Derrick White": ["DEFENSE_PER", "SPACING", "PLAYMAKER"],
    "Mike Conley": ["PLAYMAKER", "SPACING"],
    "Anfernee Simons (BOS)": ["SCORING", "SPACING"],
    "Isaiah Collier (UTA)": ["PROJECT"],
    "Bub Carrington (WAS)": ["PROJECT"],
    "Dylan Harper (SAN)": ["PROJECT"],

    // --- SHOOTING GUARDS ---
    "Devin Booker": ["SCORING", "PLAYMAKER"],
    "Jalen Williams (OKC)": ["SCORING", "DEFENSE_PER", "PLAYMAKER"],
    "Jaylen Brown": ["SCORING", "DEFENSE_PER"],
    "Tyler Herro": ["SCORING", "SPACING"],
    "Desmond Bane (ORL)": ["SCORING", "SPACING"],
    "Jalen Green (PHO)": ["SCORING"],
    "Jordan Poole (NOR)": ["SCORING"],
    "Austin Reaves (LAL)": ["SCORING", "PLAYMAKER"],
    "Zach LaVine (SAC)": ["SCORING"],
    "Alex Caruso (OKC)": ["DEFENSE_PER", "SPACING"],
    "Klay Thompson (DAL)": ["SPACING"],
    "Lu Dort": ["DEFENSE_PER"],
    "Herb Jones (NOR)": ["DEFENSE_PER"],
    "Stephon Castle (SAN)": ["DEFENSE_PER", "PROJECT"],
    "VJ Edgecombe (PHI)": ["PROJECT"],

    // --- SMALL FORWARDS ---
    "Jayson Tatum": ["SCORING", "DEFENSE_PER", "REBOUNDING"],
    "Kawhi Leonard": ["SCORING", "DEFENSE_PER"],
    "LeBron James (LAL)": ["PLAYMAKER", "SCORING", "REBOUNDING"],
    "Paul George (PHI)": ["SCORING", "DEFENSE_PER", "SPACING"],
    "Mikal Bridges (NYK)": ["SCORING", "DEFENSE_PER"],
    "Jimmy Butler (GSW)": ["SCORING", "DEFENSE_PER", "PLAYMAKER"],
    "Franz Wagner": ["SCORING", "PLAYMAKER"],
    "Brandon Miller": ["SCORING", "SPACING"],
    "Scottie Barnes": ["PLAYMAKER", "DEFENSE_PER", "REBOUNDING"],
    "Trey Murphy III": ["SPACING", "DEFENSE_PER"],
    "DeMar DeRozan (SAC)": ["SCORING"],
    "Jaden McDaniels": ["DEFENSE_PER", "SPACING"],
    "OG Anunoby (NYK)": ["DEFENSE_PER", "SPACING"],
    "Josh Hart (NYK)": ["DEFENSE_PER", "REBOUNDING"],
    "Ausar Thompson": ["DEFENSE_PER", "REBOUNDING", "PROJECT"],
    "Cooper Flagg (DAL)": ["DEFENSE_PER", "PROJECT"],
    "Matas Buzelis (CHI)": ["PROJECT"],
    "Zaccharie Risacher (ATL)": ["SPACING", "PROJECT"],
    "Dillon Brooks (PHO)": ["DEFENSE_PER"],

    // --- POWER FORWARDS ---
    "Giannis Antetokounmpo": ["SCORING", "DEFENSE_INT", "REBOUNDING", "PLAYMAKER"],
    "Nikola Jokic": ["PLAYMAKER", "SCORING", "REBOUNDING"],
    "Kevin Durant (HOU)": ["SCORING", "SPACING"],
    "Anthony Davis (DAL)": ["SCORING", "DEFENSE_INT", "REBOUNDING"],
    "Zion Williamson": ["SCORING", "PLAYMAKER"],
    "Paolo Banchero": ["SCORING", "PLAYMAKER"],
    "Victor Wembanyama": ["SCORING", "DEFENSE_INT", "SPACING", "REBOUNDING"],
    "Lauri Markkanen": ["SCORING", "SPACING"],
    "Pascal Siakam": ["SCORING", "REBOUNDING"],
    "Evan Mobley": ["DEFENSE_INT", "REBOUNDING"],
    "Chet Holmgren": ["DEFENSE_INT", "SPACING", "SCORING"],
    "Jaren Jackson Jr.": ["DEFENSE_INT", "SCORING"],
    "Julius Randle (MIN)": ["SCORING", "REBOUNDING"],
    "Aaron Gordon": ["DEFENSE_PER", "REBOUNDING"],
    "Jabari Smith Jr.": ["SPACING", "DEFENSE_INT"],
    "Keegan Murray": ["SPACING", "SCORING"],
    "Draymond Green (GSW)": ["PLAYMAKER", "DEFENSE_PER", "DEFENSE_INT"],
    "Bobby Portis": ["SCORING", "REBOUNDING"],
    "Tajan Salon": ["PROJECT"],
    "Kyle Filipowski (UTA)": ["SPACING", "PROJECT"],

    // --- CENTERS ---
    // Jokic, AD, Wemby, Chet are already listed
    "Joel Embiid": ["SCORING", "DEFENSE_INT", "REBOUNDING"],
    "Karl-Anthony Towns (NYK)": ["SCORING", "SPACING"],
    "Domantas Sabonis": ["PLAYMAKER", "REBOUNDING", "SCORING"],
    "Bam Adebayo": ["DEFENSE_INT", "PLAYMAKER", "REBOUNDING"],
    "Alperen Sengun": ["PLAYMAKER", "SCORING"],
    "Rudy Gobert": ["DEFENSE_INT", "REBOUNDING"],
    "Myles Turner (MIL)": ["SPACING", "DEFENSE_INT"],
    "Jarrett Allen": ["DEFENSE_INT", "REBOUNDING"],
    "Kristaps Porziņģis (ATL)": ["SPACING", "SCORING", "DEFENSE_INT"],
    "Walker Kessler": ["DEFENSE_INT", "REBOUNDING"],
    "Nic Claxton (BKN)": ["DEFENSE_INT", "REBOUNDING"],
    "Jalen Duren": ["REBOUNDING"],
    "Dereck Lively II": ["DEFENSE_INT", "REBOUNDING"],
    "Onyeka Okongwu": ["DEFENSE_INT"],
    "Isaiah Hartenstein (OKC)": ["DEFENSE_INT", "REBOUNDING"],
    "Deandre Ayton (LAL)": ["REBOUNDING"],
    "Clint Capela": ["REBOUNDING", "DEFENSE_INT"],
    "Zach Edey (MEM)": ["REBOUNDING", "PROJECT"],
    "Alex Sarr (WAS)": ["DEFENSE_INT", "PROJECT"],
    "Donovan Clingan (POR)": ["DEFENSE_INT", "PROJECT"],
    "Kel'el Ware (MIA)": ["PROJECT"],
    "Tony Bradley": ["PROJECT"],
    "Bol Bol": ["SPACING", "PROJECT"]
};
